BEGIN;

-- UUIDs are generated by the WSS application. They are opaque identifiers, not secrets
-- and never derived from a name, birth date, phone number, or institution customer ID.
CREATE TABLE wss_user_profiles (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'locked', 'merged', 'deleted')),
  assurance_level text NOT NULL CHECK (assurance_level IN (
    'self-asserted',
    'phone-possession',
    'institution-authenticated',
    'identity-provider-verified'
  )),
  canonical_profile_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz,
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, canonical_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  CHECK (
    (status = 'merged' AND canonical_profile_id IS NOT NULL AND canonical_profile_id <> id)
    OR (status <> 'merged' AND canonical_profile_id IS NULL)
  )
);

-- A short-lived pre-profile record. Encrypted PII is purged after completion or expiry.
CREATE TABLE wss_registration_intents (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'phone-verified', 'completed', 'expired', 'cancelled')),
  name_ciphertext bytea,
  birth_date_ciphertext bytea,
  phone_ciphertext bytea,
  phone_lookup_hash bytea NOT NULL,
  carrier_code text CHECK (carrier_code IN (
    'skt', 'kt', 'lgu-plus', 'skt-mvno', 'kt-mvno', 'lgu-plus-mvno'
  )),
  encryption_key_version smallint NOT NULL CHECK (encryption_key_version > 0),
  consent_version text NOT NULL,
  completed_profile_id uuid,
  expires_at timestamptz NOT NULL,
  pii_purged_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, completed_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  CHECK (completed_profile_id IS NULL OR status = 'completed'),
  CHECK (pii_purged_at IS NULL OR (name_ciphertext IS NULL AND birth_date_ciphertext IS NULL AND phone_ciphertext IS NULL))
);

CREATE INDEX wss_registration_intents_phone_idx
  ON wss_registration_intents (tenant_id, phone_lookup_hash, created_at DESC);

-- OTP is stored only as a server-peppered MAC. A six-digit code must never be stored
-- as plaintext or as an offline-brute-forceable unsalted hash.
CREATE TABLE wss_phone_challenges (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  registration_intent_id uuid NOT NULL,
  status text NOT NULL CHECK (status IN ('issued', 'verified', 'expired', 'blocked', 'cancelled')),
  otp_mac bytea NOT NULL,
  mac_key_version smallint NOT NULL CHECK (mac_key_version > 0),
  attempt_count smallint NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts smallint NOT NULL CHECK (max_attempts BETWEEN 1 AND 10),
  expires_at timestamptz NOT NULL,
  verified_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, registration_intent_id)
    REFERENCES wss_registration_intents (tenant_id, id),
  UNIQUE (tenant_id, id),
  CHECK ((status = 'verified' AND verified_at IS NOT NULL) OR status <> 'verified')
);

CREATE INDEX wss_phone_challenges_intent_idx
  ON wss_phone_challenges (tenant_id, registration_intent_id, created_at DESC);

-- Direct identifiers remain isolated and encrypted with a KMS-managed application key.
CREATE TABLE wss_user_private_attributes (
  tenant_id text NOT NULL,
  user_profile_id uuid NOT NULL,
  name_ciphertext bytea NOT NULL,
  birth_date_ciphertext bytea NOT NULL,
  phone_ciphertext bytea NOT NULL,
  phone_lookup_hash bytea NOT NULL,
  carrier_code text CHECK (carrier_code IN (
    'skt', 'kt', 'lgu-plus', 'skt-mvno', 'kt-mvno', 'lgu-plus-mvno'
  )),
  claim_source text NOT NULL CHECK (claim_source IN ('self-asserted', 'institution', 'identity-provider')),
  phone_possession_verified_at timestamptz,
  encryption_key_version smallint NOT NULL CHECK (encryption_key_version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (tenant_id, user_profile_id),
  FOREIGN KEY (tenant_id, user_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id)
);

CREATE INDEX wss_user_private_attributes_phone_idx
  ON wss_user_private_attributes (tenant_id, phone_lookup_hash);

-- Raw institution customer UUIDs are not persisted. The subject is a stable,
-- tenant-scoped HMAC generated with a key separate from the session-signing key.
CREATE TABLE wss_external_identities (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  user_profile_id uuid NOT NULL,
  issuer text NOT NULL,
  subject_hash text NOT NULL,
  subject_version smallint NOT NULL CHECK (subject_version > 0),
  assurance_level text NOT NULL CHECK (assurance_level IN (
    'institution-authenticated', 'identity-provider-verified'
  )),
  linked_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  UNIQUE (tenant_id, issuer, subject_version, subject_hash),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, user_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id)
);

CREATE TABLE wss_profile_merge_events (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  source_profile_id uuid NOT NULL,
  target_profile_id uuid NOT NULL,
  authorization_method text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, idempotency_key),
  FOREIGN KEY (tenant_id, source_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  FOREIGN KEY (tenant_id, target_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  CHECK (source_profile_id <> target_profile_id)
);

-- Immutable policy snapshots. Changing a tenant policy creates a new version;
-- it never rewrites the policy pinned to an existing wallet.
CREATE TABLE wss_key_policy_versions (
  tenant_id text NOT NULL,
  policy_version integer NOT NULL CHECK (policy_version > 0),
  recovery_requirement text NOT NULL CHECK (recovery_requirement IN (
    'sar-required', 'sar-preferred', 'provider-recovery-accepted'
  )),
  default_adapter text NOT NULL CHECK (default_adapter IN (
    'took-sar', 'thirdweb-user-wallet', 'fsl-mpc'
  )),
  allowed_adapters jsonb NOT NULL,
  manifest_digest text NOT NULL,
  status text NOT NULL CHECK (status IN ('draft', 'active', 'retired')),
  created_at timestamptz NOT NULL DEFAULT now(),
  activated_at timestamptz,
  retired_at timestamptz,
  PRIMARY KEY (tenant_id, policy_version),
  CHECK (jsonb_typeof(allowed_adapters) = 'array' AND jsonb_array_length(allowed_adapters) > 0),
  CHECK ((status = 'active' AND activated_at IS NOT NULL) OR status <> 'active')
);

CREATE TABLE wss_wallets (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  user_profile_id uuid NOT NULL,
  key_policy_version integer NOT NULL CHECK (key_policy_version > 0),
  key_adapter text NOT NULL CHECK (key_adapter IN (
    'took-sar', 'thirdweb-user-wallet', 'fsl-mpc'
  )),
  provisioning_origin text NOT NULL CHECK (provisioning_origin IN ('created', 'imported')),
  status text NOT NULL CHECK (status IN ('provisioning', 'active', 'suspended', 'closed')),
  label text NOT NULL,
  provisioning_idempotency_key text NOT NULL,
  secure_provision_ref_hash text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, user_profile_id, provisioning_idempotency_key),
  FOREIGN KEY (tenant_id, user_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  FOREIGN KEY (tenant_id, key_policy_version)
    REFERENCES wss_key_policy_versions (tenant_id, policy_version),
  CHECK (provisioning_origin <> 'imported' OR key_adapter = 'took-sar')
);

CREATE INDEX wss_wallets_profile_idx
  ON wss_wallets (tenant_id, user_profile_id, created_at);

CREATE TABLE wss_wallet_accounts (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  wallet_id uuid NOT NULL,
  chain_id text NOT NULL,
  address_group_id text NOT NULL,
  address_normalized text NOT NULL,
  address_display text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, chain_id, address_normalized),
  FOREIGN KEY (tenant_id, wallet_id)
    REFERENCES wss_wallets (tenant_id, id)
);

-- Contains recovery policy metadata only. SAR shares and reconstructed secrets are forbidden.
CREATE TABLE wss_sar_recovery_profiles (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  wallet_id uuid NOT NULL,
  protocol_version smallint NOT NULL CHECK (protocol_version > 0),
  threshold smallint NOT NULL,
  share_count smallint NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'active', 'rotating', 'revoked')),
  key_core_version text NOT NULL,
  storage_mode text NOT NULL CHECK (storage_mode IN ('device-only', 'single-project-development', 'separated-production')),
  policy_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, wallet_id),
  FOREIGN KEY (tenant_id, wallet_id)
    REFERENCES wss_wallets (tenant_id, id),
  CHECK (threshold >= 2 AND share_count >= threshold)
);

-- Provider account references are one-way hashes; provider secrets stay in server environments.
CREATE TABLE wss_provider_wallet_links (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  wallet_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider IN ('thirdweb-user-wallet', 'fsl-mpc')),
  provider_subject_hash text NOT NULL,
  status text NOT NULL CHECK (status IN ('active', 'revoked')),
  created_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  UNIQUE (tenant_id, provider, provider_subject_hash),
  FOREIGN KEY (tenant_id, wallet_id)
    REFERENCES wss_wallets (tenant_id, id)
);

CREATE TABLE wss_consent_records (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  user_profile_id uuid,
  registration_intent_id uuid,
  purpose_code text NOT NULL,
  document_version text NOT NULL,
  accepted_at timestamptz NOT NULL,
  revoked_at timestamptz,
  evidence_hash text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  FOREIGN KEY (tenant_id, user_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  FOREIGN KEY (tenant_id, registration_intent_id)
    REFERENCES wss_registration_intents (tenant_id, id),
  CHECK ((user_profile_id IS NOT NULL)::integer + (registration_intent_id IS NOT NULL)::integer = 1)
);

-- Key architecture changes create a new wallet and an explicit migration record.
-- The source wallet's adapter and recovery policy are never updated in place.
CREATE TABLE wss_wallet_migrations (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  source_wallet_id uuid NOT NULL,
  target_wallet_id uuid,
  from_policy_version integer NOT NULL,
  to_policy_version integer NOT NULL,
  from_adapter text NOT NULL CHECK (from_adapter IN (
    'took-sar', 'thirdweb-user-wallet', 'fsl-mpc'
  )),
  to_adapter text NOT NULL CHECK (to_adapter IN (
    'took-sar', 'thirdweb-user-wallet', 'fsl-mpc'
  )),
  status text NOT NULL CHECK (status IN (
    'planned', 'customer-approved', 'provisioning', 'transferring', 'completed', 'failed', 'cancelled'
  )),
  consent_record_id uuid,
  idempotency_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (tenant_id, idempotency_key),
  FOREIGN KEY (tenant_id, source_wallet_id)
    REFERENCES wss_wallets (tenant_id, id),
  FOREIGN KEY (tenant_id, target_wallet_id)
    REFERENCES wss_wallets (tenant_id, id),
  FOREIGN KEY (tenant_id, from_policy_version)
    REFERENCES wss_key_policy_versions (tenant_id, policy_version),
  FOREIGN KEY (tenant_id, to_policy_version)
    REFERENCES wss_key_policy_versions (tenant_id, policy_version),
  FOREIGN KEY (tenant_id, consent_record_id)
    REFERENCES wss_consent_records (tenant_id, id),
  CHECK (target_wallet_id IS NULL OR target_wallet_id <> source_wallet_id),
  CHECK ((status IN ('customer-approved', 'provisioning', 'transferring', 'completed') AND consent_record_id IS NOT NULL)
    OR status IN ('planned', 'failed', 'cancelled')),
  CHECK ((status = 'completed' AND completed_at IS NOT NULL) OR status <> 'completed')
);

CREATE TABLE wss_audit_events (
  id uuid PRIMARY KEY,
  tenant_id text NOT NULL,
  event_type text NOT NULL,
  actor_type text NOT NULL,
  actor_ref_hash text,
  user_profile_id uuid,
  wallet_id uuid,
  correlation_id text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (tenant_id, user_profile_id)
    REFERENCES wss_user_profiles (tenant_id, id),
  FOREIGN KEY (tenant_id, wallet_id)
    REFERENCES wss_wallets (tenant_id, id)
);

CREATE INDEX wss_audit_events_correlation_idx
  ON wss_audit_events (tenant_id, correlation_id, occurred_at);

-- No WSS table is available through Supabase browser roles. The Institution BFF
-- uses a direct server-side database connection. RLS is still enabled as a
-- defense-in-depth baseline before tenant-scoped policies are introduced.
DO $$
DECLARE
  table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY[
    'wss_user_profiles',
    'wss_registration_intents',
    'wss_phone_challenges',
    'wss_user_private_attributes',
    'wss_external_identities',
    'wss_profile_merge_events',
    'wss_key_policy_versions',
    'wss_wallets',
    'wss_wallet_accounts',
    'wss_sar_recovery_profiles',
    'wss_provider_wallet_links',
    'wss_consent_records',
    'wss_wallet_migrations',
    'wss_audit_events'
  ]
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', table_name);
    EXECUTE format('REVOKE ALL ON TABLE %I FROM anon, authenticated', table_name);
  END LOOP;
END $$;

COMMIT;
