/* OFFLINE UI DEMO ONLY. No network, authentication, keys or transactions.
   All values are synthetic display data. Never reuse this state engine in production. */
const iconPaths = {
 back:'<path d="m14 5-7 7 7 7"/>', close:'<path d="m6 6 12 12M18 6 6 18"/>',
 down:'<path d="m6 9 6 6 6-6"/>', chevron:'<path d="m9 5 7 7-7 7"/>',
 search:'<circle cx="10.5" cy="10.5" r="7.5"/><path d="m16 16 5 5"/>',
 bell:'<path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5zM10 21h4"/>',
 settings:'<path d="m9 3-1 3-3 1v4l-2 1 2 2v4l3 1 1 3h5l1-3 3-1v-4l2-2-2-1V7l-3-1-1-3z"/><circle cx="11.5" cy="12" r="3"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 star:'<path d="m12 3 2.8 5.7 6.3.9-4.5 4.4 1.1 6.2L12 17.3l-5.7 2.9 1.1-6.2L3 9.6l6.2-.9z"/>',
 pie:'<path d="M11 3a9 9 0 1 0 10 10H11zM15 3v6h6a8 8 0 0 0-6-6Z"/>',
 tag:'<path d="M13 3h7v7L9 21 2 14Z"/><circle cx="16.5" cy="6.5" r=".7"/>',
 menu:'<path d="M4 4h16v16H4zM4 10h16M10 4v16"/>',
 check:'<path d="m5 12 4.5 4.5L19 7"/>', info:'<circle cx="12" cy="12" r="9"/><path d="M12 10v7M12 7v.1"/>',
 shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 11 3 3 5-5"/>',
 wallet:'<rect x="3" y="5" width="18" height="15" rx="3"/><path d="M4 5V3h14M16 10h5v5h-5z"/>',
 send:'<path d="M12 20V4m-6 6 6-6 6 6"/>', receive:'<path d="M12 4v16m-6-6 6 6 6-6"/>',
 copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M16 8V3H3v14h5"/>',
 qr:'<path d="M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h3v3h3v3h-6zM12 3v3M3 12h5M12 9v6M12 21v-3M21 12h-4"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',
 more:'<circle cx="12" cy="5" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="12" cy="19" r="1"/>',
 warning:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3v.1"/>',
 refresh:'<path d="M20 8V3l-3 3a8 8 0 1 0 3 10M20 8h-5"/>',
 lock:'<rect x="5" y="10" width="14" height="11" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',
 link:'<path d="m10 7 3-3a5 5 0 0 1 7 7l-3 3M14 17l-3 3a5 5 0 0 1-7-7l3-3M8 16l8-8"/>'
};
const I=(n,small=false)=>`<svg class="kw-icon${small?' kw-icon--small':''}" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[n]||iconPaths.info}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={view:'home',network:'Ethereum',wallet:'내 지갑',amount:'50000',address:'',policy:'clear',status:'pending',history:'all'};
const demoAddress='0x1234567890abcdef1234567890abcdef12345678';
let triggerBeforeDialog=null,toastTimer;
const $=q=>document.querySelector(q);
function B(label,view,cls='',attrs=''){return `<button class="kw-button ${cls}" ${view?`data-view="${view}"`:''} ${attrs}>${label}</button>`;}
function iconButton(n,label,attrs=''){return `<button class="kw-icon-button" aria-label="${label}" ${attrs}>${I(n)}</button>`;}
function H(title,back='home',step=0){return `<header class="kw-header"><div class="kw-header__left">${back?iconButton('back','이전 화면',`data-view="${back}"`):''}</div><span class="kw-header__title">${title}</span><div class="kw-header__right">${iconButton('close','지갑 홈으로 닫기','data-action="close-flow"')}</div>${step?`<div class="kw-progress" role="progressbar" aria-valuenow="${step}" aria-valuemin="0" aria-valuemax="100" aria-label="보내기 단계"><span style="width:${step}%"></span></div>`:''}</header>`;}
function RH(title='자산'){return `<header class="kw-header kw-header--root"><img class="kw-host-logo" src="${LOGO}" alt="키움"><span class="kw-header__title">${title}</span><div class="kw-header__actions">${iconButton('search','검색','data-action="host-search"')}${iconButton('bell','알림','data-action="host-alert"')}</div></header>`;}
function nav(active='자산'){return `<nav class="kw-bottom-nav" aria-label="호스트 하단 메뉴">${[['globe','탐색'],['star','관심'],['pie','자산'],['tag','혜택'],['menu','메뉴']].map(([ic,n])=>`<button class="kw-nav-item" ${n===active?'aria-current="page"':''} data-action="host-tab" data-tab="${n}">${I(ic)}<span>${n}</span></button>`).join('')}</nav>`;}
function footer(body,flow=true){return `<footer class="kw-footer ${flow?'kw-footer--flow':''}">${body}</footer>`;}
function notice(text,type=''){return `<div class="kw-inline-notice ${type}">${I('info',true)}<span>${text}</span></div>`;}
function dataRows(rows){return `<dl class="kw-data-list">${rows.map(([k,v])=>`<div class="kw-data-row"><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl>`;}
function assetRow(sym,name,sub,val,small,view='detail'){return `<button class="kw-asset-row" data-view="${view}"><span class="kw-asset-icon kw-asset-icon--${sym==='ETH'?'eth':'usd'}">${sym==='ETH'?'ETH':'$'}</span><span class="kw-asset-info"><span class="kw-asset-name">${name}</span><span class="kw-asset-sub" style="display:block">${sub}</span></span><span class="kw-asset-value"><strong>${val}</strong><small class="kw-muted">${small}</small></span></button>`;}
function histRow(dir,label,sub,val,status){return `<button class="kw-asset-row" data-action="history-detail"><span class="kw-asset-icon" style="background:var(--kw-color-surface-lavender);color:var(--kw-color-text-purple)">${I(dir)}</span><span class="kw-asset-info"><span class="kw-asset-name">${label}</span><span class="kw-asset-sub" style="display:block">${sub}</span></span><span class="kw-asset-value"><strong>${val}</strong><small class="${status==='확인 중'?'kw-purple':'kw-muted'}">${status}</small></span></button>`;}
function flow(content,foot,title='보내기',back='home',step=33){return `<section class="kw-screen">${H(title,back,step)}<main class="kw-scroll kw-page-pad">${content}</main>${footer(foot)}</section>`;}
function home(){return `<section class="kw-screen kw-screen--root">${RH()}<main class="kw-scroll"><div class="kw-pill-tabs" role="tablist" aria-label="자산 분류"><button class="kw-pill" role="tab" aria-selected="false" data-action="host-assets">전체</button><button class="kw-pill" role="tab" aria-selected="true">디지털자산</button></div><div style="padding:20px 20px 24px"><div class="kw-between"><button class="kw-link" style="color:var(--kw-color-text-body)" data-action="wallet-sheet">${esc(state.wallet)} ${I('down',true)}</button><span class="kw-caption">예시 데이터</span></div><p class="kw-hero kw-mt-8">12,840,250원</p><p class="kw-label kw-mt-8">내 디지털자산 평가금액</p><div class="kw-actions kw-mt-24">${B('받기','receive','kw-button--secondary')}${B('보내기','recipient')}</div></div><section class="kw-card kw-card--compact"><div class="kw-between"><h2>내 자산</h2><button class="kw-link" data-view="manage">관리 ${I('chevron',true)}</button></div><div class="kw-asset-list">${assetRow('USD','USDC','Ethereum','4,620,250원','3,410.25 USDC')}${assetRow('ETH','이더리움','Ethereum','8,220,000원','2.1 ETH')}</div></section><section class="kw-card kw-card--compact"><div class="kw-between"><h2>최근 거래</h2><button class="kw-link" data-view="history">전체 ${I('chevron',true)}</button></div><div class="kw-mt-12">${histRow('receive','받기','USDC · Ethereum','+100 USDC','완료')}${histRow('send','보내기','USDC · Ethereum','−37.037 USDC','확인 중')}</div></section><div style="padding:0 20px 24px"><button class="kw-menu-row" data-view="manage"><span>지갑 관리와 복구</span>${I('chevron')}</button></div></main>${nav()}</section>`;}
function detail(){return flow(`<div class="kw-between"><span class="kw-asset-icon kw-asset-icon--usd">$</span><span class="kw-chip">USDC · ${esc(state.network)}</span></div><h1 class="kw-mt-24">USDC</h1><p class="kw-hero kw-mt-8">4,620,250원</p><p class="kw-label kw-mt-8">3,410.25 USDC</p><div class="kw-mt-32">${notice('원화 평가금액은 참고값이에요. 실제 보내는 수량은 확인 화면에서 확인해주세요.','kw-inline-notice--neutral')}</div><h2 class="kw-mt-32">거래내역</h2><div class="kw-underline-tabs kw-mt-16" role="tablist"><button role="tab" class="kw-underline-tab" aria-selected="true">전체</button><button role="tab" class="kw-underline-tab" aria-selected="false" data-view="history">보낸 내역</button><button role="tab" class="kw-underline-tab" aria-selected="false" data-view="history">받은 내역</button></div><div class="kw-mt-12">${histRow('receive','받기','09.25 · 예시','+100 USDC','완료')}${histRow('send','보내기','09.24 · 예시','−37.037 USDC','완료')}</div>`,`<div class="kw-actions">${B('받기','receive','kw-button--secondary')}${B('보내기','recipient')}</div>`,'USDC','home',0);}
function receive(){return flow(`<h2 class="kw-flow-title">이 주소로<br>디지털자산을 받을 수 있어요</h2><div class="kw-field kw-mt-32"><label>받을 자산 · 네트워크</label><button class="kw-field-select kw-field-control" data-action="network-sheet">USDC · ${esc(state.network)} ${I('down')}</button></div><div class="kw-qr-placeholder" aria-label="데모 QR 자리표시자, 스캔 불가">${I('qr')}<span>수신 주소 QR 영역</span><span class="kw-caption">데모 · 실제 QR 아님</span></div><p class="kw-address">${demoAddress}</p><p class="kw-caption" style="text-align:center;margin-top:8px">예시 주소 · 실제 송금 금지</p><div class="kw-mt-24">${notice(`USDC와 ${esc(state.network)} 네트워크를 확인해주세요. 다른 네트워크로 보내면 자산을 받지 못할 수 있어요.`)}</div>`,B(`${I('copy',true)} 주소 복사`,null,'','data-action="copy"'),'받기','home',0);}
function recipient(){const valid=/^0x[a-f0-9]{40}$/i.test(state.address);return flow(`<h2 class="kw-flow-title">누구에게 보낼까요?</h2><p class="kw-label kw-mt-12">받는 주소와 네트워크를 확인해주세요.</p><div class="kw-field kw-mt-32"><label>보낼 자산 · 네트워크</label><button class="kw-field-select kw-field-control" data-action="network-sheet">USDC · ${esc(state.network)} ${I('down')}</button></div><div class="kw-field kw-mt-32"><label for="recipient">받는 주소</label><div class="kw-field-control"><input id="recipient" autocomplete="off" autocapitalize="none" spellcheck="false" value="${esc(state.address)}" placeholder="주소를 입력해주세요" aria-describedby="address-help">${iconButton('qr','QR 스캔','data-action="scan"')}</div><p id="address-help" class="kw-caption kw-mt-8">주소 검증은 실제 서비스에서 코어가 수행해요.</p></div><button class="kw-link kw-mt-16" data-action="fill-address">데모 주소로 채우기</button><div class="kw-mt-32">${notice('이 미리보기에서는 실제 주소 확인·KYT 조회·송금이 실행되지 않아요.','kw-inline-notice--neutral')}</div>`,B('다음','amount','',`id="recipient-next" ${valid?'':'disabled'}`),'보내기','home',33);}
function amount(){return flow(`<h2 class="kw-flow-title">얼마를 보낼까요?</h2><div class="kw-between kw-mt-32"><label for="amount" class="kw-label">보낼 금액 · 원화</label><button class="kw-link" data-action="max-amount">전액</button></div><input id="amount" class="kw-amount-input" inputmode="decimal" autocomplete="off" value="${esc(state.amount)}" aria-describedby="amount-converted"><p id="amount-converted" class="kw-label kw-mt-12">약 ${(Number(state.amount||0)/1350).toFixed(6)} USDC · 예시 환산</p><div class="kw-mt-24">${dataRows([['사용 가능','3,410.25 USDC'],['네트워크',esc(state.network)],['네트워크 수수료','0.0001 ETH<br><span class="kw-caption">별도 차감 · 예시 견적</span>']])}</div><div class="kw-mt-24">${notice('다음 화면에서 토큰 수량과 수수료를 확정해요. 시세와 견적이 바뀌면 다시 확인해주세요.','kw-inline-notice--neutral')}</div>`,B('다음','review','',`id="amount-next" ${Number(state.amount)>0?'':'disabled'}`),'보내기','recipient',66);}
function policyNotice(){return state.policy==='restricted'?notice('이 서비스에서 보낼 수 없는 주소예요. 수신처를 다시 확인해주세요.','kw-inline-notice--error'):state.policy==='review'?notice('추가 확인이 필요해요. 확인이 끝난 뒤 보내기를 진행할 수 있어요.'):state.policy==='expired'?notice('수수료 견적이 만료됐어요. 정보를 다시 확인해주세요.'):notice('거래 정보 확인이 끝났어요. 위험 미탐지가 거래 안전을 보장하지는 않아요.','kw-inline-notice--neutral');}
function review(){return flow(`<h2 class="kw-flow-title">보내기 전에<br>다시 확인해주세요</h2><div class="kw-mt-24"><p class="kw-hero">${Number(state.amount||50000).toLocaleString('ko-KR')}원</p><p class="kw-label kw-mt-8">${(Number(state.amount||50000)/1350).toFixed(6)} USDC · 예시</p></div><hr class="kw-separator">${dataRows([['받는 주소',`<span style="font-size:14px">${esc(state.address||demoAddress)}</span>`],['네트워크',esc(state.network)],['받는 수량',`${(Number(state.amount||50000)/1350).toFixed(6)} USDC`],['네트워크 수수료','0.0001 ETH'],['수수료 부담','고객 · 별도 차감']])}<div class="kw-mt-20">${policyNotice()}</div><p class="kw-caption kw-mt-16">검수용 화면이에요. 실제 인증·서명·송금은 실행되지 않아요.</p>`,B(state.policy==='expired'?'견적 다시 확인':'확인하고 보내기',null,'',`data-action="${state.policy==='expired'?'refresh-quote':'approve'}" ${['restricted','review'].includes(state.policy)?'disabled':''}`),'보내기','amount',100);}
function status(){const s=state.status;const label=s==='confirmed'?'보내기가 완료됐어요':s==='failed'?'보내기를 완료하지 못했어요':s==='unknown'?'처리 결과를 확인하고 있어요':'네트워크에서<br>확인 중이에요';return flow(`<div class="kw-status-mark">${I(s==='confirmed'?'check':s==='failed'?'warning':'clock')}</div><h2 class="kw-flow-title kw-status-copy">${label}</h2><p class="kw-label kw-status-copy kw-mt-16">${s==='unknown'?'같은 거래를 다시 보내지 말고 결과를 확인해주세요.':s==='confirmed'?'네트워크 확정을 받은 상태의 화면 예시예요.':s==='failed'?'실패 사유와 재시도 가능 여부는 코어에서 받아요.':'전송 요청과 네트워크 확정은 서로 다른 단계예요.'}</p><div class="kw-mt-40">${dataRows([['상태',s==='confirmed'?'완료':s==='failed'?'실패':s==='unknown'?'결과 확인 중':'확정 대기'],['보낸 자산','USDC'],['네트워크',esc(state.network)]])}</div><div class="kw-mt-24">${notice('상태는 검수 패널에서 수동으로 바꿀 수 있어요. 실제 거래 상태가 아니에요.','kw-inline-notice--neutral')}</div>`,B('거래내역 보기','history'),'보내기','home',0);}
function historyView(){let rows='';if(state.history!=='sent') rows+=histRow('receive','받기','USDC · Ethereum','+100 USDC','완료');if(state.history!=='received')rows+=histRow('send','보내기','USDC · Ethereum','−37.037 USDC',state.status==='confirmed'?'완료':'확인 중');return flow(`<h2>거래내역</h2><div class="kw-underline-tabs kw-mt-20" role="tablist" aria-label="거래 구분">${[['all','전체'],['sent','보낸 내역'],['received','받은 내역']].map(([k,n])=>`<button role="tab" class="kw-underline-tab" aria-selected="${state.history===k}" data-action="history-filter" data-filter="${k}">${n}</button>`).join('')}</div><p class="kw-label kw-mt-24">9월 25일 · 예시</p>${rows}<p class="kw-caption kw-mt-24">실제 거래내역은 네트워크·원장 상태와 동기화해요.</p>`,B('지갑 홈으로','home','kw-button--secondary'),'거래내역','home',0);}
function manage(){return flow(`<h2>지갑 관리</h2><div class="kw-mt-24">${dataRows([['지갑 이름',esc(state.wallet)],['지갑 모드','고객 통제형<br><span class="kw-caption">프로파일 예시</span>'],['연결 네트워크',esc(state.network)]])}</div><hr class="kw-separator"><button class="kw-menu-row" data-action="recovery"><span>복구 방법 확인</span>${I('chevron')}</button><button class="kw-menu-row" data-action="host-security"><span>보안 인증 관리</span>${I('chevron')}</button><button class="kw-menu-row" data-action="wallet-sheet"><span>지갑 선택</span>${I('chevron')}</button><div class="kw-mt-24">${notice('복구 방식과 제공 기능은 지갑 프로파일을 따라요. 이 화면에서는 키나 복구 비밀을 처리하지 않아요.','kw-inline-notice--neutral')}</div>`,B('확인','home'),'지갑 관리','home',0);}
function empty(){return `<section class="kw-screen kw-screen--root">${RH()}<main class="kw-scroll"><div class="kw-pill-tabs"><button class="kw-pill" aria-selected="true">디지털자산</button></div><section class="kw-card kw-mt-20"><div class="kw-empty-illustration">${I('wallet')}</div><h2 style="text-align:center">아직 지갑이 없어요</h2><p class="kw-body kw-mt-16" style="text-align:center">키움 앱 안에서<br>디지털자산을 관리해보세요.</p><div class="kw-mt-32">${B('지갑 만들기',null,'','data-action="create-wallet"')}</div><div style="text-align:center;margin-top:16px"><button class="kw-link" data-action="recovery">기존 지갑 복구하기 ${I('chevron',true)}</button></div></section></main>${nav()}</section>`;}
function refForm(carrier=false){return flow(`<h2 class="kw-flow-title">안전한 투자를 위해<br>본인 확인을 해볼게요</h2><div class="kw-field" style="margin-top:28px"><label for="ref-name">${carrier?'통신사':'이름'}</label><div class="kw-field-control">${carrier?`<button class="kw-field-select" data-action="carrier-sheet" style="color:var(--kw-color-text-placeholder)">통신사 선택 ${I('down')}</button>`:'<input id="ref-name" placeholder="이름을 입력해주세요" aria-invalid="true" aria-describedby="ref-error">'}</div>${carrier?'':'<p class="kw-error" id="ref-error">이름을 다시 확인해주세요</p>'}</div>`,B('인증번호 받기',null,'','disabled'),'휴대폰 본인인증',null,20);}
function rank(){const data=[['N','엔비디아','NVDA','225.0700','0.22%','#82BA00'],['A','애플','AAPL','341.0700','1.53%','#3D4654'],['3x','SOXL','미국 반도체 3배 디렉…','151.4500','3.50%','#D70080'],['M','마이크론 테크놀…','MU','1,082.2800','0.16%','#078FB8'],['SK','SK하이닉스(AD…','SKHY','191.5600','2.78%','#F0F0F0']];return `<section class="kw-screen kw-screen--root">${RH('탐색')}<main class="kw-scroll"><div class="kw-pill-tabs"><button class="kw-pill">국내</button><button class="kw-pill" aria-selected="true">미국</button><button class="kw-pill">ETF</button><span class="kw-chip" style="margin-left:auto;padding:0 8px">$　<span class="kw-muted">원</span></span></div><div class="kw-ref-markets"><div>S&amp;P 500 ›<br><b>7,743.41</b> <span class="kw-up">+0.51%</span></div><div>나스닥 ›<br><b>27,068.72</b> <span class="kw-up">+0.48%</span></div></div><section class="kw-card" style="margin-top:12px"><h2>실시간 랭킹 TOP5</h2><div class="kw-underline-tabs kw-mt-16" style="gap:18px"><button class="kw-underline-tab" aria-selected="true">많이보는</button><button class="kw-underline-tab">많이사는</button><button class="kw-underline-tab">많이파는</button><button class="kw-underline-tab">가격급등</button></div><div class="kw-asset-list">${data.map(([l,n,t,v,p,c],i)=>`<div class="kw-asset-row" style="gap:9px"><span class="kw-label" style="color:var(--kw-color-text-body)">${i+1}</span><span class="kw-asset-icon" style="background:${c};color:${i===4?'#D64239':'white'}">${l}</span><span class="kw-asset-info"><span class="kw-asset-name">${n}</span><span class="kw-asset-sub" style="display:block">${t}</span></span><span class="kw-asset-value kw-up"><strong>${v}</strong><small>${p}</small></span></div>`).join('')}</div><div style="margin-top:14px">${B('더보기',null,'kw-button--quiet','data-action="ref-info"')}</div></section></main>${nav('탐색')}</section>`;}
function components(){return flow(`<h2>컴포넌트</h2><p class="kw-label kw-mt-8">스크린샷 기반 규격 예시</p><div class="kw-mt-24">${B('다음',null,'','data-action="toast-example"')}</div><div class="kw-mt-12">${B('받기',null,'kw-button--secondary','data-view="receive"')}</div><div class="kw-mt-12">${B('다음',null,'','disabled')}</div><div class="kw-actions kw-mt-24">${B('팔게요',null,'kw-button--sell','data-action="ref-info"')}${B('살게요',null,'kw-button--buy','data-action="ref-info"')}</div><p class="kw-caption kw-mt-8">매수/매도 전용 의미. 받기/보내기에 적용하지 않음.</p><div class="kw-field kw-mt-32"><label for="component-field">입력 라벨</label><div class="kw-field-control"><input id="component-field" placeholder="내용을 입력해주세요"></div></div><div class="kw-mt-24">${notice('설명과 안내를 표시하는 보조 영역이에요.')}</div><div class="kw-mt-20">${B('네트워크 선택 시트',null,'kw-button--quiet','data-action="network-sheet"')}</div>`,B('지갑 홈으로','home','kw-button--secondary'),'컴포넌트','home',0);}
const renders={home,detail,receive,recipient,amount,review,status,history:historyView,manage,empty,'ref-form':()=>refForm(),'ref-sheet':()=>refForm(true),'ref-rank':rank,components};
const labels={home:'W01 · 지갑 홈',detail:'W02 · 자산 상세',receive:'W03 · 받기',recipient:'W04 · 보내기 / 수신처',amount:'W05 · 보내기 / 금액',review:'W06 · 보내기 / 확인',status:'W07 · 처리 상태',history:'W08 · 거래내역',manage:'W09 · 지갑 관리',empty:'W00 · 지갑 없음','ref-form':'R16 · 폼 규격 검수','ref-sheet':'R15 · 시트 규격 검수','ref-rank':'R10 · 루트 규격 검수',components:'C01 · 컴포넌트'};
function render(){clearTimeout(toastTimer);$('#app').innerHTML=renders[state.view]();if($('#screen-select'))$('#screen-select').value=state.view;if($('#view-name'))$('#view-name').textContent=labels[state.view];document.querySelectorAll('[data-panel-view]').forEach(b=>b.classList.toggle('active',b.dataset.panelView===state.view));const ref={'ref-form':'R16','ref-sheet':'R15','ref-rank':'R10'}[state.view];if($('#overlay-controls'))$('#overlay-controls').hidden=!ref;if($('#source-note'))$('#source-note').textContent=ref?`${ref}와 비교하는 규격 샘플입니다. 폰트·아이콘은 임시이므로 완전 일치 결과가 아닙니다. 시세는 원본 캡처의 표시값으로, 현재 시세가 아닙니다.`:'신규 지갑 적용안입니다. 첨부 앱에 실제로 존재하는 화면이 아니며, 모든 잔액·주소·수수료는 가상값입니다.';if($('#ref-overlay')){ $('#ref-overlay').src=ref?REFS[ref]:'';$('#ref-overlay').style.opacity=ref?($('#overlay-slider').value/100):0;$('#ref-overlay').hidden=!ref;}if(state.view==='ref-sheet')openSheet('carrier',true);}
function go(view){if(!renders[view])return;closeSheet(false);state.view=view;render();if(!new URLSearchParams(location.search).has('embed')){try{window.history.replaceState(null,'','#'+view);}catch{/* srcdoc preview has no navigable URL */}}}
function toast(text){document.querySelector('.kw-toast')?.remove();const t=document.createElement('div');t.className='kw-toast';t.role='status';t.textContent=text;$('#app').appendChild(t);clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.remove(),3500);}
function openSheet(type,noFocus=false){closeSheet(false);triggerBeforeDialog=document.activeElement;let title='',body='';if(type==='network'){title='네트워크 선택';body=`<div class="kw-sheet-options">${['Ethereum','Base','Polygon'].map(n=>`<button class="kw-choice" aria-pressed="${state.network===n}" data-action="choose-network" data-value="${n}">${n}${state.network===n?I('check',true):''}</button>`).join('')}</div><p class="kw-caption kw-mt-16">예시 목록입니다. 실제 지원 네트워크는 코어에서 받아요.</p>`;}if(type==='wallet'){title='지갑 선택';body=`<div class="kw-sheet-options">${['내 지갑','생활비 지갑'].map(n=>`<button class="kw-choice" aria-pressed="${state.wallet===n}" data-action="choose-wallet" data-value="${n}">${n}${state.wallet===n?I('check',true):''}</button>`).join('')}</div>`;}if(type==='carrier'){title='통신사 선택';body=`<div class="kw-sheet-options">${['SKT','KT','LGU+','SKT알뜰폰','KT알뜰폰','LGU+알뜰폰'].map(n=>`<button class="kw-choice" data-action="choose-carrier">${n}</button>`).join('')}</div>`;}if(type==='approval'){title='보내기 승인';body=`<p class="kw-body kw-mt-20">실제 서비스에서는 키움의 보안 인증과 코어 서명 흐름으로 연결해요.</p><div class="kw-mt-20">${notice('아래 버튼은 데모 상태만 변경해요. 인증·서명·송금이 실행되지 않아요.','kw-inline-notice--neutral')}</div><div class="kw-mt-24">${B('데모 승인',null,'','data-action="demo-approved"')}</div>`;}if(type==='exit'){title='보내기를 그만할까요?';body=`<p class="kw-body kw-mt-20">작성 중인 정보를 지우고 지갑 홈으로 이동해요.</p><div class="kw-actions kw-mt-24">${B('계속 작성',null,'kw-button--secondary','data-action="close-sheet"')}${B('그만하기',null,'','data-action="discard"')}</div>`;}if(type==='recovery'){title='복구 방법 확인';body=`<p class="kw-body kw-mt-20">지갑 코어가 제공하는 복구 프로파일에 따라 안내와 본인인증으로 연결해요.</p><div class="kw-mt-20">${notice('이 예제는 복구구문·키 조각·인증 비밀을 입력받지 않아요.','kw-inline-notice--neutral')}</div><div class="kw-mt-24">${B('확인',null,'','data-action="close-sheet"')}</div>`;}
 const layer=document.createElement('div');layer.className='kw-sheet-layer';layer.innerHTML=`<div class="kw-sheet-scrim" data-action="close-sheet" aria-hidden="true"></div><section class="kw-sheet" role="dialog" aria-modal="true" aria-labelledby="sheet-title" tabindex="-1"><button class="kw-icon-button kw-sheet-close" aria-label="시트 닫기" data-action="close-sheet">${I('close')}</button><h2 class="kw-sheet-title" id="sheet-title">${title}</h2>${body}</section>`;$('#app').querySelector('.kw-screen')?.setAttribute('inert','');$('#app').appendChild(layer);if(!noFocus)layer.querySelector('.kw-sheet').focus();}
function closeSheet(restore=true){const s=document.querySelector('.kw-sheet-layer');if(!s)return;s.remove();$('#app').querySelector('.kw-screen')?.removeAttribute('inert');if(restore&&triggerBeforeDialog?.isConnected)triggerBeforeDialog.focus();}
document.addEventListener('keydown',e=>{const d=document.querySelector('[role="dialog"]');if(!d)return;if(e.key==='Escape'){closeSheet();return;}if(e.key==='Tab'){const f=[...d.querySelectorAll('button:not(:disabled),[href],input:not(:disabled),[tabindex="0"]')];if(!f.length){e.preventDefault();return;}const first=f[0],last=f[f.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===d)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===d)){e.preventDefault();first.focus();}}});
document.addEventListener('input',e=>{if(e.target.id==='recipient'){state.address=e.target.value.trim();$('#recipient-next').disabled=!/^0x[a-f0-9]{40}$/i.test(state.address);}if(e.target.id==='amount'){state.amount=e.target.value.replace(/[^0-9.]/g,'');const n=Number(state.amount);$('#amount-next').disabled=!(n>0&&Number.isFinite(n));$('#amount-converted').textContent=`약 ${Number.isFinite(n)?(n/1350).toFixed(6):'—'} USDC · 예시 환산`;}if(e.target.id==='overlay-slider')$('#ref-overlay').style.opacity=e.target.value/100;});
document.addEventListener('change',e=>{if(e.target.id==='screen-select')go(e.target.value);if(e.target.id==='policy-select'){state.policy=e.target.value;go('review');}if(e.target.id==='status-select'){state.status=e.target.value;go('status');}});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action],[data-view],[data-panel-view]');if(!b||b.disabled)return;if(b.dataset.view){go(b.dataset.view);return;}if(b.dataset.panelView){go(b.dataset.panelView);return;}switch(b.dataset.action){case 'network-sheet':openSheet('network');break;case 'wallet-sheet':openSheet('wallet');break;case 'carrier-sheet':openSheet('carrier');break;case 'choose-network':state.network=b.dataset.value;state.policy='clear';closeSheet(false);if(['review','amount'].includes(state.view)){state.view='recipient';state.address='';}render();toast('네트워크 예시 변경 · 실제 서비스는 주소/견적을 재검증해요.');break;case 'choose-wallet':state.wallet=b.dataset.value;closeSheet(false);render();break;case 'close-sheet':closeSheet();break;case 'choose-carrier':closeSheet();toast('규격 확인용 선택행입니다. 본인인증은 실행되지 않아요.');break;case 'fill-address':state.address=demoAddress;render();break;case 'max-amount':state.amount='100000';render();toast('전액 버튼의 가상값입니다. 실제 전액은 코어에서 계산해요.');break;case 'approve':if(state.policy==='clear')openSheet('approval');break;case 'demo-approved':state.status='pending';go('status');break;case 'refresh-quote':state.policy='clear';$('#policy-select').value='clear';render();toast('새 견적을 받은 상태의 예시로 변경했어요.');break;case 'history-filter':state.history=b.dataset.filter;render();break;case 'history-detail':go('status');break;case 'recovery':openSheet('recovery');break;case 'create-wallet':toast('실서비스는 약관/호스트 인증/코어 생성 흐름으로 연결해요.');break;case 'close-flow':if(['recipient','amount','review'].includes(state.view)&&(state.address||state.amount))openSheet('exit');else go('home');break;case 'discard':state.address='';state.amount='50000';go('home');break;case 'copy':try{await navigator.clipboard.writeText(demoAddress);toast('예시 주소를 복사했어요. 실제 송금에는 사용하지 마세요.');}catch{toast('로컬 파일에서는 복사가 제한될 수 있어요. 주소 텍스트를 선택해주세요.');}break;case 'host-tab':b.dataset.tab==='자산'?go('home'):toast(`${b.dataset.tab} 탭은 실제 키움 앱으로 연결하는 영역이에요.`);break;case 'scan':toast('실서비스는 호스트 QR 스캔으로 연결해요.');break;case 'ref-info':toast('사용자 제공 화면의 규격 참고입니다. 실거래 버튼이 아니에요.');break;case 'toast-example':toast('안내 메시지 예시예요.');break;default:toast('호스트 앱이 제공하는 기능으로 연결하는 영역이에요.');}});
const q=new URLSearchParams(location.search);if(q.get('embed')==='1')document.body.classList.add('is-embedded');if(renders[q.get('view')])state.view=q.get('view');else if(renders[location.hash.slice(1)])state.view=location.hash.slice(1);render();

window.addEventListener('message',e=>{if(e.source===window.parent && e.data?.type==='kw-demo-view' && renders[e.data.view])go(e.data.view);});
